In [1]:
# Importing dependencies
import pandas as pd
import numpy as np

In [3]:
# Opening datasets needed for analysis

rat_data = pd.read_csv('clean_csv/final_rat_sightings.csv')
rest_data = pd.read_csv('clean_csv/final_rat_violations.csv')
weather_data = pd.read_csv('clean_csv/final_weather.csv')

In [4]:
rat_data.head()

,Unnamed: 0,Incident ID,Sighting Date,Complaint Type,Incident,Location Type,Incident Zip,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Latitude,Longitude
0,0,31464015,2015-09-04,Rodent,Rat Sighting,3+ Family Mixed Use Building,10006,Manhattan,980656.0,197137.0,40.707772,-74.012963
1,1,31464024,2015-09-04,Rodent,Rat Sighting,Commercial Building,10306,Staten Island,955207.0,148858.0,40.575209,-74.104547
2,2,31464025,2015-09-04,Rodent,Rat Sighting,1-2 Family Dwelling,10310,Staten Island,949033.0,169278.0,40.631236,-74.126878
3,3,31464026,2015-09-04,Rodent,Rat Sighting,3+ Family Apt. Building,11206,Brooklyn,1000550.0,197585.0,40.708987,-73.941207
4,4,31464027,2015-09-04,Rodent,Rat Sighting,3+ Family Mixed Use Building,10462,Bronx,1021648.0,250489.0,40.854130,-73.864813

In [5]:
rest_data.head()

,Unnamed: 0,index,Violation ID,Borough,Incident Zip,Violation Date,Violation Description,Critical Flag
0,0,3,50061389,Staten Island,10314,2017-05-17,Cold food item held above 41Âº F (smoked fish ...,Critical
1,1,6,50058069,Brooklyn,11215,2017-06-22,Evidence of rats or live rats present in facil...,Critical
2,2,7,40807238,Staten Island,10304,2017-06-14,Cold food item held above 41Âº F (smoked fish ...,Critical
3,3,8,41547684,Staten Island,10310,2015-03-10,Cold food item held above 41Âº F (smoked fish ...,Critical
4,4,9,40376944,Manhattan,10012,2015-10-06,Cold food item held above 41Âº F (smoked fish ...,Critical

2